project_id = "lcnaptefceboratxhzox"

[functions.asaas]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.client-auth]
verify_jwt = false

[functions.payment-reminders]
verify_jwt = false