project_id = "lcnaptefceboratxhzox"

[functions.asaas]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.client-auth]
verify_jwt = false

[functions.payment-reminders]
verify_jwt = false

[functions.affiliate-auth]
verify_jwt = false

[functions.affiliate-approval-email]
verify_jwt = false

[functions.mercadopago]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false
